### ISSUE TITLE
Possible to change the limit of the news that it provides?

### ISSUE THREAD

**Issue by snaildos** [win11react/NewsAPI#4]
~35 is a really small amount. Possible to do 60-70?
Kind regards,
Snail

**Comment by yashash1511** [comment]
Sorry for the late reply @snaildos for that you can fork this repo and https://github.com/win11react/NewsAPI/blob/fd0d34cb1423d6c0ba7d1ba5af5e1b950cfc580c/.github/workflows/main.yml#L14 change this to `endpoint: https://newsapi.org/v2/top-headlines?language=en&pageSize=70&apiKey=${{ secrets.NEWSAPI_KEY }}`

note the pageSize parameter is changed to 70 from 35 earlier

**Comment by snaildos** [comment]
> Sorry for the late reply @snaildos, now answering to your query you can fork this repo and
> 
> https://github.com/win11react/NewsAPI/blob/fd0d34cb1423d6c0ba7d1ba5af5e1b950cfc580c/.github/workflows/main.yml#L14
> 
> change this to `endpoint: https://newsapi.org/v2/top-headlines?language=en&pageSize=70&apiKey=${{ secrets.NEWSAPI_KEY }}`
> note the pageSize parameter is changed to 70 from 35 earlier
> 
> i am looking for ways in which the users will be able to change these parameters but that might take time ~or might not even happen ever~.

Appreciating the reply, thank you.
